In [2]:
import requests
import pprint
import json
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

### API 받아오기

In [2]:
pageno = 1
#nrow = 10000
year = 2018
df = pd.DataFrame()

In [3]:
for i in range(0, 5):
    pageno = 1
    while pageno <= 18:
        url = 'http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo={0}&numOfRows=10000&resultType=json&yr={1}'.format(pageno, year)
        response = requests.get(url)
        dict = json.loads(response.text)
        doc = dict["items"]
        df = pd.concat([df, pd.DataFrame(doc)], axis = 0, ignore_index = True)

        print(url)
        pageno += 1
        
    year += 1

http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=1&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=2&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=3&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=4&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=5&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=6&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=7&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=8&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=9&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=10&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=11&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=12&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=13&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=14&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=15&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=16&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=17&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=18&numOfRows=10000&resultType=json&yr=2018
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=1&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=2&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=3&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=4&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=5&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=6&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=7&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=8&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=9&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=10&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=11&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=12&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=13&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=14&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=15&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=16&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=17&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=18&numOfRows=10000&resultType=json&yr=2019
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=1&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=2&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=3&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=4&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=5&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=6&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=7&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=8&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=9&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=10&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=11&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=12&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=13&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=14&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=15&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=16&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=17&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=18&numOfRows=10000&resultType=json&yr=2020
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=1&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=2&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=3&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=4&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=5&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=6&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=7&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=8&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=9&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=10&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=11&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=12&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=13&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=14&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=15&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=16&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=17&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=18&numOfRows=10000&resultType=json&yr=2021
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=1&numOfRows=10000&resultType=json&yr=2022
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=2&numOfRows=10000&resultType=json&yr=2022
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=3&numOfRows=10000&resultType=json&yr=2022
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=4&numOfRows=10000&resultType=json&yr=2022
http://apis.data.go.kr/1130000/FftcBrandFrcsUnitAvrSalInfoService/getBrandFrcsUnitAvrSalInfo?serviceKey=Xa9F%2BlohBnyap8Pj%2FHmyDdz%2FozVb5GFsC5z06uWip4HPt7n2yNTwF8UqP3Oq%2F%2Fx2M78iBDteaqxGceksQRSxdA%3D%3D&pageNo=5&numOfRows=10000&resultType=json&yr=2022

In [4]:
df

,jngIfrmpRgsno,brandNm,indutyLclasNm,indutyMlsfcNm,yr,areaNm,frcsCnt,avrgSlsAmt,arUnitAvrgSlsAmt,crrncyUnitCdNm,rlvtYn
0,20080100006,잉글리쉬무무,서비스,교육 (외국어),2018,강원,7.0,56294.0,NaN,(단위 :천원),N
1,20080100006,잉글리쉬무무,서비스,교육 (외국어),2018,경기,76.0,43422.0,NaN,(단위 :천원),N
2,20080100006,잉글리쉬무무,서비스,교육 (외국어),2018,경남,42.0,46783.0,NaN,(단위 :천원),N
3,20080100006,잉글리쉬무무,서비스,교육 (외국어),2018,경북,6.0,47486.0,NaN,(단위 :천원),N
4,20080100006,잉글리쉬무무,서비스,교육 (외국어),2018,광주,32.0,49194.0,NaN,(단위 :천원),N
...,...,...,...,...,...,...,...,...,...,...,...
732494,20231689,하라김밥,외식,한식,2022,전북,0.0,0.0,0.0,(단위 :천원),None
732495,20231689,하라김밥,외식,한식,2022,전체,0.0,0.0,0.0,(단위 :천원),None
732496,20231689,하라김밥,외식,한식,2022,제주,0.0,0.0,0.0,(단위 :천원),None
732497,20231689,하라김밥,외식,한식,2022,충남,0.0,0.0,0.0,(단위 :천원),None
732498,20231689,하라김밥,외식,한식,2022,충북,0.0,0.0,0.0,(단위 :천원),None

In [5]:
df.isnull().sum()

jngIfrmpRgsno            0
brandNm                  0
indutyLclasNm            0
indutyMlsfcNm            0
yr                       0
areaNm                   0
frcsCnt              76643
avrgSlsAmt          163128
arUnitAvrgSlsAmt    163462
crrncyUnitCdNm           0
rlvtYn              418903
dtype: int64

In [6]:
df['indutyLclasNm'].value_counts()

indutyLclasNm
외식     581616
서비스    116305
도소매     34578
Name: count, dtype: int64

In [7]:
len(df.loc[df['indutyLclasNm'] == '외식'])

581616

### 외식 업종만 추출

In [8]:
df2 = df[df['indutyLclasNm'] == '외식']

In [9]:
df2

,jngIfrmpRgsno,brandNm,indutyLclasNm,indutyMlsfcNm,yr,areaNm,frcsCnt,avrgSlsAmt,arUnitAvrgSlsAmt,crrncyUnitCdNm,rlvtYn
36,20080100014,이디야커피,외식,커피,2018,강원,75.0,227950.0,7226.0,(단위 :천원),N
37,20080100014,이디야커피,외식,커피,2018,경기,613.0,219743.0,10709.0,(단위 :천원),N
38,20080100014,이디야커피,외식,커피,2018,경남,136.0,192643.0,6421.0,(단위 :천원),N
39,20080100014,이디야커피,외식,커피,2018,경북,80.0,184106.0,7315.0,(단위 :천원),N
40,20080100014,이디야커피,외식,커피,2018,광주,45.0,243401.0,12594.0,(단위 :천원),N
...,...,...,...,...,...,...,...,...,...,...,...
732494,20231689,하라김밥,외식,한식,2022,전북,0.0,0.0,0.0,(단위 :천원),None
732495,20231689,하라김밥,외식,한식,2022,전체,0.0,0.0,0.0,(단위 :천원),None
732496,20231689,하라김밥,외식,한식,2022,제주,0.0,0.0,0.0,(단위 :천원),None
732497,20231689,하라김밥,외식,한식,2022,충남,0.0,0.0,0.0,(단위 :천원),None
732498,20231689,하라김밥,외식,한식,2022,충북,0.0,0.0,0.0,(단위 :천원),None

In [10]:
df2.to_csv('브랜드가맹점단위면적당평균매출액.csv', index=False)

In [4]:
df3 = pd.read_csv('브랜드가맹점단위면적당평균매출액.csv', encoding='utf-8-sig')

In [5]:
df3

,가맹정보공개서등록번호,브랜드명,업종대분류명,업종중분류명,기준년도,지역명,가맹점수,평균매출금액,면적단위평균매출금액,화폐단위코드명,해당여부
0,20080100014,이디야커피,외식,커피,2018,강원,75.0,227950.0,7226.0,(단위 :천원),N
1,20080100014,이디야커피,외식,커피,2018,경기,613.0,219743.0,10709.0,(단위 :천원),N
2,20080100014,이디야커피,외식,커피,2018,경남,136.0,192643.0,6421.0,(단위 :천원),N
3,20080100014,이디야커피,외식,커피,2018,경북,80.0,184106.0,7315.0,(단위 :천원),N
4,20080100014,이디야커피,외식,커피,2018,광주,45.0,243401.0,12594.0,(단위 :천원),N
...,...,...,...,...,...,...,...,...,...,...,...
581611,20231689,하라김밥,외식,한식,2022,전북,0.0,0.0,0.0,(단위 :천원),NaN
581612,20231689,하라김밥,외식,한식,2022,전체,0.0,0.0,0.0,(단위 :천원),NaN
581613,20231689,하라김밥,외식,한식,2022,제주,0.0,0.0,0.0,(단위 :천원),NaN
581614,20231689,하라김밥,외식,한식,2022,충남,0.0,0.0,0.0,(단위 :천원),NaN
581615,20231689,하라김밥,외식,한식,2022,충북,0.0,0.0,0.0,(단위 :천원),NaN

### 서울, 전체 데이터 추출

In [8]:
df_seo_tot = df3[(df3["지역명"] == "서울") | (df3["지역명"] == "전체")]

In [10]:
df_seo_tot.to_csv('브랜드가맹점단위면적당평균매출액(서울+전체).csv', index=False)

### 2022년 기준 데이터 추출

In [13]:
df4 = df3[df3["기준년도"] == 2022]
df4

,가맹정보공개서등록번호,브랜드명,업종대분류명,업종중분류명,기준년도,지역명,가맹점수,평균매출금액,면적단위평균매출금액,화폐단위코드명,해당여부
442224,20080100033,피자에땅,외식,피자,2022,강원,14.0,154236.0,9634.0,(단위 :천원),NaN
442225,20080100033,피자에땅,외식,피자,2022,경기,35.0,114134.0,7697.0,(단위 :천원),NaN
442226,20080100033,피자에땅,외식,피자,2022,경남,18.0,134707.0,7119.0,(단위 :천원),NaN
442227,20080100033,피자에땅,외식,피자,2022,경북,15.0,158012.0,8279.0,(단위 :천원),NaN
442228,20080100033,피자에땅,외식,피자,2022,광주,0.0,0.0,0.0,(단위 :천원),NaN
...,...,...,...,...,...,...,...,...,...,...,...
581611,20231689,하라김밥,외식,한식,2022,전북,0.0,0.0,0.0,(단위 :천원),NaN
581612,20231689,하라김밥,외식,한식,2022,전체,0.0,0.0,0.0,(단위 :천원),NaN
581613,20231689,하라김밥,외식,한식,2022,제주,0.0,0.0,0.0,(단위 :천원),NaN
581614,20231689,하라김밥,외식,한식,2022,충남,0.0,0.0,0.0,(단위 :천원),NaN
581615,20231689,하라김밥,외식,한식,2022,충북,0.0,0.0,0.0,(단위 :천원),NaN

In [14]:
df_seo_tot_2022 = df4[(df4["지역명"] == "서울") | (df4["지역명"] == "전체")]
df_seo_tot_2022

,가맹정보공개서등록번호,브랜드명,업종대분류명,업종중분류명,기준년도,지역명,가맹점수,평균매출금액,면적단위평균매출금액,화폐단위코드명,해당여부
442232,20080100033,피자에땅,외식,피자,2022,서울,12.0,88210.0,6454.0,(단위 :천원),NaN
442238,20080100033,피자에땅,외식,피자,2022,전체,184.0,139856.0,7918.0,(단위 :천원),NaN
442250,20080100034,오븐에빠진닭,외식,치킨,2022,서울,21.0,587173.0,17615.0,(단위 :천원),NaN
442256,20080100034,오븐에빠진닭,외식,치킨,2022,전체,70.0,321424.0,11027.0,(단위 :천원),NaN
442268,20080100047,놀부보쌈족발,외식,한식,2022,서울,16.0,140594.0,9864.0,(단위 :천원),N
...,...,...,...,...,...,...,...,...,...,...,...
581576,20231687,닭발주는 코바꼬 바베큐치킨,외식,치킨,2022,전체,0.0,NaN,NaN,(단위 :천원),N
581588,20231688,개떡카페,외식,커피,2022,서울,0.0,0.0,0.0,(단위 :천원),N
581594,20231688,개떡카페,외식,커피,2022,전체,0.0,0.0,0.0,(단위 :천원),N
581606,20231689,하라김밥,외식,한식,2022,서울,0.0,0.0,0.0,(단위 :천원),NaN
581612,20231689,하라김밥,외식,한식,2022,전체,0.0,0.0,0.0,(단위 :천원),NaN

In [15]:
df_seo_tot_2022.to_csv('브랜드가맹점단위면적당평균매출액(서울+전체+2022년).csv', index=False)